# Generated by Django 4.1.5 on 2023-01-29 19:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acumulado', models.BooleanField()),
                ('dataApuracao', models.DateField()),
                ('dataProximoConcurso', models.DateField(blank=True, null=True)),
                ('dezenasSorteadasOrdemSorteio', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=6), size=None)),
                ('exibirDetalhamentoPorCidade', models.BooleanField()),
                ('indicadorConcursoEspecial', models.IntegerField()),
                ('listaDezenas', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=6), size=None)),
                ('listaDezenasSegundoSorteio', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), size=6), size=None)),
                ('listaMunicipioUFGanhadores', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=6), size=None)),
                ('localSorteio', models.CharField(blank=True, max_length=50)),
                ('nomeMunicipioUFSorteio', models.CharField(max_length=50)),
                ('nomeTimeCoracaoMesSorte', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.IntegerField()),
                ('numeroConcursoAnterior', models.IntegerField()),
                ('numeroConcursoFinal_0_5', models.IntegerField()),
                ('numeroConcursoProximo', models.IntegerField()),
                ('numeroJogo', models.IntegerField()),
                ('premiacaoContingencia', models.TextField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('tipoJogo', models.CharField(max_length=50)),
                ('tipoPublicacao', models.IntegerField()),
                ('ultimoConcurso', models.BooleanField()),
                ('valorArrecadado', models.FloatField()),
                ('valorAcumuladoConcurso_0_5', models.FloatField()),
                ('valorAcumuladoConcursoEspecial', models.FloatField()),
                ('valorAcumuladoProximoConcurso', models.FloatField()),
                ('valorEstimadoProximoConcurso', models.FloatField()),
                ('valorSaldoReservaGarantidora', models.FloatField()),
                ('valorTotalPremioFaixaUm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RateioPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoFaixa', models.CharField(max_length=50)),
                ('faixa', models.IntegerField()),
                ('numeroDeGanhadores', models.IntegerField()),
                ('valorPremio', models.FloatField()),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loteria.concurso')),
            ],
        ),
    ]
