# Generated by Django 3.2.16 on 2023-03-03 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0002_aluno_categoria_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loteria.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loteria.curso')),
            ],
        ),
    ]
